-- Your SQL goes here
ALTER TABLE games 
	ADD COLUMN research_diff INT NOT NULL DEFAULT 2,
	ADD COLUMN research_rand BOOLEAN NOT NULL DEFAULT TRUE,
	ADD COLUMN hof_size INT NOT NULL DEFAULT 10,
	ADD COLUMN global_size INT NOT NULL DEFAULT 5,
	ADD COLUMN indepstr INT NOT NULL DEFAULT 5,
	ADD COLUMN magicsites INT NOT NULL DEFAULT 40,
	ADD COLUMN eventrarity INT NOT NULL DEFAULT 2,
	ADD COLUMN richness INT NOT NULL DEFAULT 100,
	ADD COLUMN resources INT NOT NULL DEFAULT 100,
	ADD COLUMN recruitment INT NOT NULL DEFAULT 100,
	ADD COLUMN supplies INT NOT NULL DEFAULT 100,
	ADD COLUMN startprov INT NOT NULL DEFAULT 2,
	ADD COLUMN renaming BOOLEAN NOT NULL DEFAULT FALSE,
	ADD COLUMN scoregraphs BOOLEAN NOT NULL DEFAULT TRUE,
	ADD COLUMN nationinfo BOOLEAN NOT NULL DEFAULT TRUE,
	ADD COLUMN artrest BOOLEAN NOT NULL DEFAULT FALSE,
	ADD COLUMN teamgame BOOLEAN NOT NULL DEFAULT FALSE,
	ADD COLUMN clustered BOOLEAN NOT NULL DEFAULT FALSE,
	ADD COLUMN storyevents INT NOT NULL DEFAULT 1,
	ADD COLUMN newailvl INT NOT NULL DEFAULT 2,
	ADD COLUMN newai BOOLEAN NOT NULL DEFAULT TRUE;

